// <auto-generated />
using CarPlace_Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarPlace_Backend.Migrations
{
    [DbContext(typeof(ZoomCarContext))]
    partial class ZoomCarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarPlace_Backend.Models.CarDetails", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CarImage");

                    b.Property<string>("CarOwnerName");

                    b.Property<string>("CarOwnerNumber");

                    b.Property<int>("ModelId");

                    b.Property<double>("Price");

                    b.Property<bool>("Status");

                    b.HasKey("CarId");

                    b.HasIndex("ModelId");

                    b.ToTable("CarDetails");
                });

            modelBuilder.Entity("CarPlace_Backend.Models.CarModel", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName");

                    b.Property<string>("ModelName");

                    b.HasKey("ModelId");

                    b.ToTable("CarModel");
                });

            modelBuilder.Entity("CarPlace_Backend.Models.OrderDetails", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId");

                    b.Property<string>("Email");

                    b.Property<int>("ZoomCarUserId");

                    b.HasKey("OrderId");

                    b.HasIndex("CarId");

                    b.HasIndex("ZoomCarUserId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CarPlace_Backend.Models.ZoomCarUser", b =>
                {
                    b.Property<int>("ZoomCarUserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FullName");

                    b.Property<string>("Password");

                    b.Property<int>("UserId");

                    b.HasKey("ZoomCarUserId");

                    b.ToTable("ZoomCarUser");
                });

            modelBuilder.Entity("CarPlace_Backend.Models.CarDetails", b =>
                {
                    b.HasOne("CarPlace_Backend.Models.CarModel", "CarModel")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CarPlace_Backend.Models.OrderDetails", b =>
                {
                    b.HasOne("CarPlace_Backend.Models.CarDetails", "CarDetails")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarPlace_Backend.Models.ZoomCarUser", "user")
                        .WithMany()
                        .HasForeignKey("ZoomCarUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
